package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const (
	generateComment = "generate:reset"
	generatedFile   = "reset.gen.go"
)

type structInfo struct {
	Name string
	Type *ast.StructType
}

type packageInfo struct {
	Dir            string
	PkgName        string
	Structs        []structInfo
	TypesWithReset map[string]bool
}

type generator struct {
	fset        *token.FileSet
	packages    map[string]*packageInfo
	zeroCounter int
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	g := &generator{
		fset:     token.NewFileSet(),
		packages: make(map[string]*packageInfo),
	}

	if err := g.scan(root); err != nil {
		log.Fatal(err)
	}

	if err := g.generate(); err != nil {
		log.Fatal(err)
	}
}

func (g *generator) scan(root string) error {
	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			name := d.Name()
			if strings.HasPrefix(name, ".") || name == "vendor" {
				return filepath.SkipDir
			}
			return nil
		}

		if filepath.Ext(path) != ".go" {
			return nil
		}

		if strings.HasSuffix(path, "_test.go") {
			return nil
		}

		if filepath.Base(path) == generatedFile {
			return nil
		}

		return g.parseFile(path)
	})
}

func (g *generator) parseFile(path string) error {
	file, err := parser.ParseFile(g.fset, path, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	dir := filepath.Dir(path)
	pkgName := file.Name.Name
	key := dir + ":" + pkgName

	pkg, ok := g.packages[key]
	if !ok {
		pkg = &packageInfo{
			Dir:            dir,
			PkgName:        pkgName,
			TypesWithReset: make(map[string]bool),
		}
		g.packages[key] = pkg
	}

	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			if d.Tok != token.TYPE {
				continue
			}
			for _, spec := range d.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				if !hasGenerateComment(d, typeSpec) {
					continue
				}

				pkg.Structs = append(pkg.Structs, structInfo{
					Name: typeSpec.Name.Name,
					Type: structType,
				})
			}
		case *ast.FuncDecl:
			if d.Recv == nil || len(d.Recv.List) == 0 {
				continue
			}
			if d.Name == nil || d.Name.Name != "Reset" {
				continue
			}

			recvType := d.Recv.List[0].Type
			switch rt := recvType.(type) {
			case *ast.Ident:
				pkg.TypesWithReset[rt.Name] = true
			case *ast.StarExpr:
				if ident, ok := rt.X.(*ast.Ident); ok {
					pkg.TypesWithReset[ident.Name] = true
				}
			}
		}
	}

	return nil
}

func hasGenerateComment(gen *ast.GenDecl, spec *ast.TypeSpec) bool {
	if hasCommentWithMarker(spec.Doc) {
		return true
	}
	if hasCommentWithMarker(spec.Comment) {
		return true
	}
	if hasCommentWithMarker(gen.Doc) {
		return true
	}
	return false
}

func hasCommentWithMarker(group *ast.CommentGroup) bool {
	if group == nil {
		return false
	}

	for _, c := range group.List {
		if strings.Contains(c.Text, generateComment) {
			return true
		}
	}

	return false
}

func (g *generator) generate() error {
	for _, pkg := range g.packages {
		if len(pkg.Structs) == 0 {
			continue
		}

		// Types that either already have Reset or will have it generated.
		hasReset := make(map[string]bool, len(pkg.TypesWithReset)+len(pkg.Structs))
		for name := range pkg.TypesWithReset {
			hasReset[name] = true
		}
		for _, s := range pkg.Structs {
			hasReset[s.Name] = true
		}

		var buf bytes.Buffer

		buf.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n")
		buf.WriteString("\n")
		buf.WriteString("package " + pkg.PkgName + "\n\n")

		g.zeroCounter = 0

		for _, s := range pkg.Structs {
			// Do not overwrite manually implemented Reset methods.
			if pkg.TypesWithReset[s.Name] {
				continue
			}
			g.generateResetMethod(&buf, s, hasReset)
		}

		if buf.Len() == 0 {
			continue
		}

		src := buf.Bytes()
		formatted, err := format.Source(src)
		if err != nil {
			// In case of formatting error, fall back to unformatted source
			formatted = src
		}

		outPath := filepath.Join(pkg.Dir, generatedFile)
		if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
			return err
		}
	}

	return nil
}

func (g *generator) generateResetMethod(buf *bytes.Buffer, s structInfo, hasReset map[string]bool) {
	buf.WriteString("func (s *" + s.Name + ") Reset() {\n")
	buf.WriteString("\tif s == nil {\n")
	buf.WriteString("\t\treturn\n")
	buf.WriteString("\t}\n")

	if s.Type.Fields != nil {
		for _, field := range s.Type.Fields.List {
			if len(field.Names) == 0 {
				// Embedded field.
				name := embeddedFieldName(field.Type)
				if name == "" {
					continue
				}
				expr := "s." + name
				lines := g.resetLines(expr, field.Type, hasReset)
				for _, line := range lines {
					buf.WriteString("\t" + line + "\n")
				}
				continue
			}

			for _, name := range field.Names {
				expr := "s." + name.Name
				lines := g.resetLines(expr, field.Type, hasReset)
				for _, line := range lines {
					buf.WriteString("\t" + line + "\n")
				}
			}
		}
	}

	buf.WriteString("}\n\n")
}

func embeddedFieldName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		if t.Sel != nil {
			return t.Sel.Name
		}
	}
	return ""
}

func (g *generator) resetLines(expr string, t ast.Expr, hasReset map[string]bool) []string {
	switch tt := t.(type) {
	case *ast.Ident:
		if hasReset[tt.Name] {
			return []string{expr + ".Reset()"}
		}
		switch tt.Name {
		case "bool":
			return []string{expr + " = false"}
		case "string":
			return []string{expr + ` = ""`}
		case "error":
			return []string{expr + " = nil"}
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"float32", "float64",
			"complex64", "complex128",
			"byte", "rune":
			return []string{expr + " = 0"}
		default:
			typeStr := g.exprString(tt)
			if typeStr == "" {
				return nil
			}
			zero := g.nextZeroIdent()
			return []string{
				"var " + zero + " " + typeStr,
				expr + " = " + zero,
			}
		}
	case *ast.ArrayType:
		// Slice type: []T
		if tt.Len == nil {
			return []string{expr + " = " + expr + "[:0]"}
		}
		// Fixed-size array: use zero value.
		typeStr := g.exprString(tt)
		if typeStr == "" {
			return nil
		}
		zero := g.nextZeroIdent()
		return []string{
			"var " + zero + " " + typeStr,
			expr + " = " + zero,
		}
	case *ast.MapType:
		return []string{
			"if " + expr + " != nil {",
			"\tclear(" + expr + ")",
			"}",
		}
	case *ast.StarExpr:
		// Pointer to type that has Reset method.
		if ident, ok := tt.X.(*ast.Ident); ok && hasReset[ident.Name] {
			return []string{
				"if " + expr + " != nil {",
				"\t" + expr + ".Reset()",
				"}",
			}
		}

		// Pointer to pointer: just reset pointer itself.
		if _, ok := tt.X.(*ast.StarExpr); ok {
			return []string{expr + " = nil"}
		}

		// Pointer to other types: reset the value it points to.
		innerExpr := "*" + expr
		innerLines := g.resetLines(innerExpr, tt.X, hasReset)
		if len(innerLines) == 0 {
			return []string{expr + " = nil"}
		}

		lines := []string{"if " + expr + " != nil {"}
		for _, line := range innerLines {
			lines = append(lines, "\t"+line)
		}
		lines = append(lines, "}")
		return lines
	case *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		return []string{expr + " = nil"}
	case *ast.SelectorExpr, *ast.StructType:
		typeStr := g.exprString(tt)
		if typeStr == "" {
			return nil
		}
		zero := g.nextZeroIdent()
		return []string{
			"var " + zero + " " + typeStr,
			expr + " = " + zero,
		}
	default:
		typeStr := g.exprString(tt)
		if typeStr == "" {
			return nil
		}
		zero := g.nextZeroIdent()
		return []string{
			"var " + zero + " " + typeStr,
			expr + " = " + zero,
		}
	}
}

func (g *generator) exprString(expr ast.Expr) string {
	var buf bytes.Buffer
	if err := format.Node(&buf, g.fset, expr); err != nil {
		return ""
	}
	return strings.TrimSpace(buf.String())
}

func (g *generator) nextZeroIdent() string {
	name := "zero" + strconv.Itoa(g.zeroCounter)
	g.zeroCounter++
	return name
}
